export const SET_ACCOUNTS = 'SET_ACCOUNTS';
export const SET_ACCOUNTS_ERROR = 'SET_ACCOUNTS_ERROR';
export const SET_WALLET_CREATE = 'SET_WALLET_CREATE';

export const OPEN_WALLET = 'OPEN_WALLET';
export const OPEN_WALLET_ERROR = 'OPEN_WALLET_ERROR';

export const HAS_WALLET = 'HAS_WALLET';

export const ERROR_PERSONA_DATA = 'ERROR_PERSONA_DATA';

export const ADD_PERSONA_DATA = 'ADD_PERSONA_DATA';

export const RUNNING_METHOD = 'RUNNING_METHOD';